// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace spellboundapi.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20181103031638_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("spellbound_api.Models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AtHigherLevels")
                        .IsRequired();

                    b.Property<string>("CastingTime")
                        .IsRequired();

                    b.Property<string>("ComponentsSerialized")
                        .IsRequired()
                        .HasColumnName("Components");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Duration")
                        .IsRequired();

                    b.Property<int>("Level");

                    b.Property<string>("Materials")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Range")
                        .IsRequired();

                    b.Property<string>("Reference")
                        .IsRequired();

                    b.Property<string>("School")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
