// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace spellboundapi.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("spellbound_api.Models.ClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SpellId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("ClassType");
                });

            modelBuilder.Entity("spellbound_api.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SpellId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("Component");
                });

            modelBuilder.Entity("spellbound_api.Models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AtHigherLevels")
                        .IsRequired();

                    b.Property<string>("CastingTime")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Duration")
                        .IsRequired();

                    b.Property<int>("Level");

                    b.Property<string>("Materials")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Range")
                        .IsRequired();

                    b.Property<string>("Reference")
                        .IsRequired();

                    b.Property<string>("School")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("spellbound_api.Models.ClassType", b =>
                {
                    b.HasOne("spellbound_api.Models.Spell")
                        .WithMany("ClassTypes")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("spellbound_api.Models.Component", b =>
                {
                    b.HasOne("spellbound_api.Models.Spell")
                        .WithMany("Components")
                        .HasForeignKey("SpellId");
                });
#pragma warning restore 612, 618
        }
    }
}
